pool:
  vmImage: 'ubuntu-16.04'

container: mcr.microsoft.com/dotnet/core/sdk:3.1

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration release'